#!/usr/bin/env sh

# Copied from https://github.com/ryan4yin/nix-config

# wiki 要求在配置最前面加这个，看起来是跟 sudo 权限相关的东西
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

## Debug
yabai -m config debug_output on

# 窗口平铺
yabai -m space --layout bsp
# 默认拆分规则 first_child second_child
yabai -m config window_placement             second_child
# 窗口间距设置
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10
# 自动平衡所有窗口始终占据相同的空间
yabai -m config auto_balance                 off
# 如果禁用自动平衡，此项属性定义的是新窗口占用的空间量。0.5意为旧窗口占用50%
yabai -m config split_ratio                 0.50
# 鼠标修饰键 意思就是按着这个键就可以使用鼠标单独修改窗口大小了
yabai -m config mouse_modifier ctrl
# ctrl + 鼠标左键 移动窗口
yabai -m config mouse_action1 move
# ctrl + 鼠标右键 调整窗口大小
yabai -m config mouse_action2 resize
# 焦点跟随鼠标 默认off: 关闭  autoraise:自动提升 autofocus: 自动对焦
yabai -m config focus_follows_mouse          autofocus
# 设置鼠标是否跟随当前活动窗口 默认 off: 关闭 on: 开启
yabai -m config mouse_follows_focus          off

yabai -m config window_border       on
yabai -m config window_border_width 2
yabai -m config window_gap          10

# 在所有显示器上的每个空间顶部添加 0 填充 底部添加 0 填充
yabai -m config external_bar all:0:0

# ================================ 规则 ================================

yabai -m rule --add title='Preferences' manage=off layer=above
yabai -m rule --add title='Library' manage=off layer=above
yabai -m rule --add app='^System Preferences$' manage=off layer=above
yabai -m rule --add app='^Activity Monitor' manage=off layer=above
yabai -m rule --add app='^Finder' manage=off layer=above
yabai -m rule --add app='^System Information$' manage=off layer=above
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements" manage=off

echo "yabai configuration loaded.."
