keys:
  - &ashebanow age1kqrklqk8cln654tvwxh94lshtu45ps9ujh05crjdphxnm73vfamsyje6ak
  - &lumquat age1sqxyva9etc72nye4rxar0pzpkqhqtaahqkr34duxzedwch8mn3fslvvuu8

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *ashebanow
          - *lumquat
