"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:green)\
${env_var.ZMX_SESSION}\
$os\
$username\
$hostname\
[ ](fg:green)\
[](fg:yellow)\
$shell\
$directory\
[ ](fg:yellow)\
[](fg:pink)\
$git_branch\
$git_status\
[ ](fg:pink)\
$line_break$character"""

# languages section
# [](fg:blue)\
# ${custom.nixlang}\
# $pixi\
# $ruby\
# $rust\
# $golang\
# $nodejs\
# $python\
# $c\
# [ ](fg:blue)\

palette = 'catppuccin_mocha'

# see https://github.com/catppuccin/starship/blob/main/starship.toml
[palettes.catppuccin_mocha]
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

[os]
disabled = false
style = "bg:green fg:crust"
format = '[$symbol ]($style)'

[os.symbols]
Alpine = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
Linux = ""
Macos = ""
NixOS = ""
Pop = ""
RedHatEnterprise = ""
Redhat = ""
SUSE = ""
Ubuntu = ""
Windows = ""

[username]
show_always = true
style_user = "bg:green fg:crust"
style_root = "bg:green fg:red"
format = '[$user]($style)'

[hostname]
ssh_only = false
ssh_symbol = '@'
style = "bg:green fg:crust"
trim_at = '.'
disabled = false
format = '[@$hostname ]($style)'

[env_var.ZMX_SESSION]
symbol = " "
format = "[$symbol$env_value ]($style)"
description = "zmx session name"
style = "bg:green fg:crust"

[shell]
disabled = false
style = "fg:crust bg:yellow"
fish_indicator = '🐟'
zsh_indicator = ''
format = "[$indicator ]($style)"

[directory]
style = "fg:crust bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:pink"
format = '[[ $symbol $branch ](fg:crust bg:pink)]($style)'

[git_status]
style = "bg:pink"
format = '[[($all_status$ahead_behind )](fg:crust bg:pink)]($style)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[custom.nixlang]
command = "nix --version | awk '{ print $NF }'"
detect_extensions = ['nix']
format = '[ $symbol $output ]($style)'
style = "fg:crust bg:blue"
symbol = '󱄅'

[pixi]
style = "fg:crust bg:blue"
format = '[ $symbol$environment ]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[ruby]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:base"
format = '[[  $time ](fg:crust bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
