{
  flake.nixosModules.hostLumquat = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  { config, lib, pkgs, modulesPath, ... }:

  {
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
    boot.initrd.kernelModules = [ "amd_iommu=off" "amdgpu.gttsize=126976" "ttm.pages_limit=32505856" ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/mapper/luks-2363ecb6-9c4e-4c6a-a948-1e5e24089470";
        fsType = "ext4";
      };

    boot.initrd.luks.devices."luks-2363ecb6-9c4e-4c6a-a948-1e5e24089470".device = "/dev/disk/by-uuid/2363ecb6-9c4e-4c6a-a948-1e5e24089470";

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/8A6E-4E07";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
