#!/usr/bin/env bash

dest_machine=$1
dest_ip=""

case "$dest_machine" in
  storage )
    dest_ip="10.40.0.226";;
  limon )
    dest_ip="10.40.60.7";;
  yuzu )
    dest_ip="10.40.60.6";;
  miraclemax )
    dest_ip="10.4.0.44";;
  nixos-wsl )
    dest_ip=" 172.21.75.8";;
  gateway )
    dest_ip="10.40.0.1";;
  * )
    echo "Usage: copy-ssh-keys dest_machine"
    echo "  dest_machine must be one of:"
    echo "    gateway"
    echo "    storage"
    echo "    limon"
    echo "    miraclemax"
    echo "    nixos-wsl"
    echo "    yuzu"
    exit 1
    ;;
esac

if [ ! -f ~/.ssh/id_ed25519 ]; then
  echo "No ~/.ssh/id_ed25519 file found"
  exit 1
fi

if [ ! -f ~/.ssh/github_ed25519 ]; then
  echo "No ~/.ssh/github_ed25519 file found"
  exit 1
fi

if [ ! -f ~/.ssh/cattivi_unifi ]; then
  echo "No ~/.ssh/cattivi_unifi file found"
  exit 1
fi

echo "Copying private keys to $dest_ip($dest_machine)..."
scp -A -p -r ~/.ssh/id_ed25519 ~/.ssh/github_ed25519 ~/.ssh/cattivi_unifi \
  "ashebanow@$dest_ip:/home/ashebanow/.ssh/"
echo Done
