#!/usr/bin/env bash

dest_machine=$1
dest_ip=""

case "$dest_machine" in
  storage )
    dest_ip="10.40.0.226";;
  nixos-mac-aarch64 )
    dest_ip="10.211.55.10";;
  virt1 )
    dest_ip="10.40.0.43";;
  virt2 )
    dest_ip="10.40.0.73";;
  loquat )
    dest_ip="10.40.0.118";;
  miraclemax )
    dest_ip="10.4.0.44";;
  gateway )
    dest_ip="10.40.0.1";;
  * )
    echo "Usage: copy-ssh-keys.sh dest_machine"
    echo "  dest_machine must be one of:"
    echo "    gateway"
    echo "    nixos-mac-aarch64"
    echo "    storage"
    echo "    virt1"
    echo "    virt2"
    echo "    loquat"
    echo "    miraclemax"
    exit 1
    ;;
esac

if [ ! -f ~/.ssh/id_ed25519 ]; then
  echo "No ~/.ssh/id_ed25519 file found"
  exit 1
fi

if [ ! -f ~/.ssh/github_ed25519 ]; then
  echo "No ~/.ssh/github_ed25519 file found"
  exit 1
fi

echo "Copying private keys to $dest_ip($dest_machine)..."
scp -A -p -r ~/.ssh/id_ed25519 ~/.ssh/github_ed25519 \
  "ashebanow@$dest_ip:/home/ashebanow/.ssh/"
echo Done
