#!/bin/bash

for dir in $(find . -name '.git' -type d)
do
    dir=$(dirname $dir)
    cd $dir

    STATE=""

    if [[ -n $(git ls-files --other --exclude-standard 2> /dev/null) ]]; then
        STATE="untracked-files ${STATE}"
    fi

    if ! git diff --quiet 2> /dev/null; then
        STATE="modified ${STATE}"
    fi

    if ! git diff --cached --quiet 2> /dev/null; then
        STATE="staged ${STATE}"
    fi

    if [[ -n $STATE ]]; then
        echo "${dir}: ${STATE}"
    fi

    cd - > /dev/null
done