#!/usr/bin/env bash

STARSHIP_CONFIG="~/nix-config/dotfiles/starship.toml"
STARSHIP_BINARY=`command -v starship`

# cd ~/Development/homelab/homelab-cattivi

PROMPT="$($STARSHIP_BINARY prompt \
    --terminal-width=132 \
    --keymap=KEYMAP \
    --status=STARSHIP_CMD_STATUS \
    --pipestatus=STARSHIP_PIPE_STATUS \
    --cmd-duration=STARSHIP_DURATION \
    --jobs=2)"
