# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

# Lumquat hardware configuration — Strix Halo (GMKTec Evo X2).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid"
    "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  # Initrd modules for AMD GPU and storage
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "sdhci_pci"
    "ahci"
    "amdgpu"
    "radeon"
  ];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Strix Halo kernel params for LLM GPU passthrough
  # See: https://github.com/hellas-ai/nix-strix-halo
  boot.kernelParams = [
    "amd_iommu=off" # Required for Strix Halo stability
    "amdgpu.gttsize=126976" # Expose ~124 GB VRAM to GPU
    "ttm.pages_limit=32505856" # Full memory pool for TTM
  ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2363ecb6-9c4e-4c6a-a948-1e5e24089470";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2363ecb6-9c4e-4c6a-a948-1e5e24089470".device = "/dev/disk/by-uuid/2363ecb6-9c4e-4c6a-a948-1e5e24089470";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # AMD GPU
  hardware.graphics.enable = lib.mkDefault true;
  hardware.graphics.enable32Bit = lib.mkDefault true;
}
